#!/bin/bash

# Hardware watchdog configuration tutorial by Ricardo Arturo Cabral
# http://blog.ricardoarturocabral.com/2013/01/auto-reboot-hung-raspberry-pi-using-on.html

# Load the module the next time the system boots
echo "bcm2708_wdog" | sudo tee -a /etc/modules

# Install the software watchdog daemon and make sure it runs after every boot
sudo apt-get install watchdog
sudo update-rc.d watchdog defaults
echo "@reboot sudo /etc/init.d/watchdog start" >> /var/spool/cron/crontabs/root

# Configure the watchdog daemon
sed -i 's/#watchdog-device/watchdog-device/g' /etc/watchdog.conf
sed -i 's/#max-load-/max-load-/g' /etc/watchdog.conf

# Start the watchdog daemon
/etc/init.d/watchdog start
