#!/bin/bash

# Hardware watchdog configuration tutorial by Glen "vk5tu" Turner
# http://vk5tu.livejournal.com/35721.html

# Install watchdog daemon
apt-get install watchdog
update-rc.d watchdog enable

# Watchdog daemon configuration
> /etc/watchdog.conf
echo "watchdog-device = /dev/watchdog" >> /etc/watchdog.conf
echo "watchdog-timeout = 14" >> /etc/watchdog.conf
echo "realtime = yes" >> /etc/watchdog.conf
echo "priority = 1" >> /etc/watchdog.conf
echo "interval = 1" >> /etc/watchdog.conf

# User space heart beat - systemd configuration
sep -i 's/#RuntimeWatchdogSec=0/RuntimeWatchdogSec=14/g' /etc/systemd/system.conf

# Configure kernel watchdog device
> /etc/modprobe.d/bcm2708_wdog.conf
echo "alias char-major-10-130 bcm2708_wdog" >> /etc/modprobe.d/bcm2708_wdog.conf
echo "alias char-major-10-131 bcm2708_wdog" >> /etc/modprobe.d/bcm2708_wdog.conf
echo "options bcm2708_wdog heartbeat=14 nowayout=1" >> /etc/modprobe.d/bcm2708_wdog.conf

sep -i 's/watchdog_module=""/watchdog_module="bcm2708_wdog"/g' /etc/default/watchdog

# Start watchdog service
modprobe bcm2708_wdog
service watchdog start
